name: visualpremium
description: "Desvende o poder da organização financeira com este aplicativo de orçamento desktop, que oferece uma interface intuitiva para gerenciar orçamentos, produtos e materiais, tudo com um toque de elegância nos modos claro e escuro."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  shared_preferences: ^2.0.0
  intl: 0.20.2
  fl_chart: 0.68.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.2
  go_router: ^16.2.0
  http: 1.6.0
  network_info_plus: ^4.0.0
  path_provider: ^2.1.1
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
      - assets/images/

flutter_launcher_icons:
  windows:
    generate: true
    icon_size: 256
  image_path: assets/images/logo.png

