name: visualpremium
description: "Software Visual Premium"
publish_to: "none"
version: 1.0.1+1


environment:
  sdk: ^3.6.0

dependencies:
  shared_preferences: ^2.0.0
  intl: 0.20.2
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.0
  provider: ^6.1.2
  go_router: ^17.0.1
  http: 1.6.0
  network_info_plus: ^7.0.0
  path_provider: ^2.1.1
  url_launcher: ^6.3.1
  window_manager: ^0.5.1
  flutter_dotenv: ^5.1.0
  package_info_plus: ^8.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
      - .env
      - .env.dev

      - assets/images/logo.png
      - assets/images/logo branca.png
      - assets/images/logo preta.png
      - assets/images/logo pretaInicio.png

flutter_launcher_icons:
  windows:
    generate: true
    icon_size: 256
  image_path: assets/images/logo.png

